<?xml version="1.0" encoding="utf-8"?>
<ActionCollection version="2" name="Scripts">
    <Actions category="Scripts">
        <text>Krita UI Tweaks</text>
        <Action name="krita_ui_tweaks">
            <icon></icon>
            <text>Krita UI Tweaks</text>
            <whatsThis></whatsThis>
            <toolTip></toolTip>
            <iconText></iconText>
            <activationFlags>0</activationFlags>
            <activationConditions>0</activationConditions>
            <shortcut></shortcut>
            <isCheckable>false</isCheckable>
            <statusTip></statusTip>
        </Action>
        <Action name="krita_ui_tweaks_toggle_dockers">
            <icon></icon>
            <text>Toggle docking</text>
        </Action>
        <Action name="krita_ui_tweaks_next_tab">
            <icon></icon>
            <text>Goto next tab</text>
        </Action>
        <Action name="krita_ui_tweaks_prev_tab">
            <icon></icon>
            <text>Goto previous tab</text>
        </Action>
        <Action name="krita_ui_tweaks_save_layout_as">
            <icon></icon>
            <text>Save Split Layout As…</text>
        </Action>
        <Action name="krita_ui_tweaks_save_layout">
            <icon></icon>
            <text>Save Layout</text>
        </Action>
        <Action name="krita_ui_tweaks_load_layout">
            <icon></icon>
            <text>Load Layout</text>
        </Action>
        <Action name="krita_ui_tweaks_toggle_layout_lock">
            <icon></icon>
            <text>Toggle Layout Locked</text>
        </Action>
        <Action name="krita_ui_tweaks_scaling_mode_anchored">
            <icon></icon>
            <text>Scaling Mode Anchored</text>
        </Action>
        <Action name="krita_ui_tweaks_scaling_mode_contained">
            <icon></icon>
            <text>Scaling Mode Contained</text>
        </Action>
        <Action name="krita_ui_tweaks_scaling_mode_expanded">
            <icon></icon>
            <text>Scaling Mode Expanded</text>
        </Action>
        <Action name="krita_ui_tweaks_center_canvas">
            <icon></icon>
            <text>Center Canvas</text>
        </Action>
    </Actions>
</ActionCollection>
